# Generated by Django 4.0.6 on 2022-07-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crudDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namedb', models.CharField(max_length=50)),
                ('emaildb', models.CharField(max_length=50)),
                ('phonedb', models.CharField(max_length=50)),
            ],
        ),
    ]
